version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: price_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: price_bot
    env_file:
      - .env
    environment:
      - API_URL=http://price_api:8000/search/v2
    depends_on:
      - api

  avito_worker:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: price_avito_worker
    command: python -m app.workers.ingest_avito
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  notifications_worker:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: price_notifications_worker
    command: python -m app.workers.notifications
    env_file:
      - .env
    depends_on:
      - postgres
      - api
    restart: always

  postgres:
    image: postgres:16
    container_name: price_postgres
    environment:
      POSTGRES_DB: price_aggregator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: price_redis
    ports:
      - "6379:6379"

volumes:
  pg_data:
